{% set name = "multiviewica" %}
{% set version = "0.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multiviewica-{{ version }}.tar.gz
  sha256: 36c96009b1a785108883f8d2dbc5a06baa1cbb5afdfd641eeefed271ee5b1985

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - fastsrm
    - matplotlib-base >=2.0.0
    - numpy >=1.12
    - python >={{ python_min }}
    - python-picard
    - scikit-learn >=0.23
    - scipy >=0.18.0

test:
  imports:
    - multiviewica
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/multiviewica/
  summary: Multi-view ICA
  license_file: ./LICENSE
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - hoechenberger
    - hugorichard
